version: 2
jobs:
  build_test_deploy:
    working_directory: ~/rendeer
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run: 'npm install'
      - run: 'npm run lint'

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test_deploy
